### ISSUE TITLE
No enough information to know why dispatch call failed

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-messages-sol#156]
The call to s2s send_message is successful(evm tx) but the call is not executed to the ending (there is no `MessageAccepted`).  There is no enough information for the sdk user to know what happened.

**Comment by wuminzhe** [comment]
https://github.com/darwinia-network/darwinia-common/issues/1194

**Comment by wuminzhe** [comment]
[test.txt](https://github.com/darwinia-network/darwinia-bridges-sol/files/8559606/test.txt)

**Comment by AsceticBear** [comment]
```sh
DispatchErrorWithPostInfo { post_info: PostDispatchInfo { actual_weight: None, pays_fee: Pays::Yes }, error: BadOrigin } 
```

@wuminzhe

**Comment by wuminzhe** [comment]
> ```shell
> DispatchErrorWithPostInfo { post_info: PostDispatchInfo { actual_weight: None, pays_fee: Pays::Yes }, error: BadOrigin } 
> ```
> 
> @wuminzhe

thanks

**Comment by AurevoirXavier** [comment]
Should this issue belong to darwinia-common?

**Comment by AsceticBear** [comment]
Just keep it this repo. There is another issue in darwinia-common https://github.com/darwinia-network/darwinia-common/issues/1194
