### ISSUE TITLE
CrabSmartchain to Darwinia cross-chain failure

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-messages-sol#163]
I failed to invoke Darwinia's `remark` call from Crab Smartchain with solidity SDK. 

The tx or ex related are:

1. send message
    https://crab.subscan.io/tx/0x6933834e12fc21a8db21be2e23e7d906904db34cce54e57aec5b778fdc91e07b

2. receive_messages_proof
    https://darwinia.subscan.io/extrinsic/8437597-1

3. receive_messages_delivery_proof
    https://crab.subscan.io/extrinsic/10401582-1

My problems：
1. `send_message` call does not appear in the crab's extrinsics.
2. `remark` dispatched at Darwinia，but there is no remark extrinsic, nor does the `Remarked` event
3. receive_messages_delivery_proof transaction failed, but  I got only `Revert`.

**Comment by HackFisher** [comment]
> send_message call does not appear in the crab's extrinsics.

Yes, `send_message` is a dispatch call embedded to be part of the evm tx, not an standalone extrinsic.

> remark dispatched at Darwinia，but there is no remark extrinsic, nor does the Remarked event
Suggest to use `remartWithEvent` instead, it will emit event.  Same with above one, this is part of the message delivery tx, not standalone extrinsic, be clear between the difference between concepts of dispatch call and extrinsic.

**Comment by HackFisher** [comment]
But the crab runtime seems to only support remark for now:

https://github.com/darwinia-network/darwinia/blob/b5e79a93359855f20f6f9f1bcf89e8749f9316d1/runtime/crab/src/pallets/bridge_dispatch.rs#L15

A pull request to darwinia repo is required to support `remartWithEvent `

**Comment by wuminzhe** [comment]
remark is filtered out on darwinia? I didn't see any info about it.

**Comment by HackFisher** [comment]
> receive_messages_delivery_proof transaction failed, but I got only Revert.

This is cause by the bad implementation of `OnDeliveryConfirmed`:

[OnDeliveryConfirmed](https://github.com/darwinia-network/darwinia/blob/main/runtime/crab/src/pallets/bridge_messages.rs#L40-L41)

Need to be fixed and generalized:

cc @xiaoch05

**Comment by HackFisher** [comment]
> But the crab runtime seems to only support remark for now:
> 
> https://github.com/darwinia-network/darwinia/blob/b5e79a93359855f20f6f9f1bcf89e8749f9316d1/runtime/crab/src/pallets/bridge_dispatch.rs#L15
> 
> A pull request to darwinia repo is required to support `remarkWithEvent `

My mistake, it already support `frame_system::Call::remark_with_event`


https://github.com/darwinia-network/darwinia/blob/b5e79a93359855f20f6f9f1bcf89e8749f9316d1/runtime/crab/src/pallets/bridge_dispatch.rs#L16

**Comment by HackFisher** [comment]
Use https://github.com/darwinia-network/darwinia-common/pull/1250 to prepare the companion for darwinia/crab runtime.

**Comment by wuminzhe** [comment]
fixed
