### ISSUE TITLE
Does the return data of precompile need abi.encode?

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-messages-sol#200]
I prefer to remove `abi_encode_bytes` as it adds an unnecessary encoding and decoding process.
```
Ok(PrecompileOutput {
	exit_status: ExitSucceed::Returned,
	cost: helper.used_gas(),
	output: abi_encode_bytes(&output.unwrap_or_default()), <---
	logs: Default::default(),
})
```

**Comment by AsceticBear** [comment]
It's not entirely correct.  If playing with smart contracts with remix, it will do ethabi decode automatically. If we remove it, the code remix shows are wrong.
