### ISSUE TITLE
Require `_data.length` > 0

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-messages-sol#230]
https://github.com/darwinia-network/darwinia-messages-sol/blob/28ec79482a0d5ef500fe1ce066c51165f4efe75c/contracts/periphery/contracts/s2s/types/CommonTypes.sol#L81

**Comment by wuminzhe** [comment]
I'll fix it. Under what conditions will the data length be 0?

**Comment by wuminzhe** [comment]
the type of `AssignedRelayers` is `Option<Vec<PalletFeeMarketRelayer>>`.

* if AssignedRelayers is None:
  the storage data return is null

* if AssignedRelayers is Some([...])
  the storage data return is scale bytes of type `Vec<PalletFeeMarketRelayer>`
