### ISSUE TITLE
Wrong decode of DeliveredMessages.dispatch_results 

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-messages-sol#239]
https://github.com/darwinia-network/darwinia-messages-sol/blob/b0fcd4b78911a5306405dcea861875cc0dce1f73/contracts/periphery/contracts/s2s/types/CommonTypes.sol#L152

https://github.com/darwinia-network/darwinia-messages-substrate/blob/c3f10155a2650850ffa8998e5f98617e1aded55a/primitives/messages/src/lib.rs#L192

DeliveredMessages.dispatch_results  is `BitVec<u8, Msb0>` not `bytes1`

**Comment by wuminzhe** [comment]
review needed: https://github.com/darwinia-network/darwinia-messages-sol/pull/240
