### ISSUE TITLE
Multi relayer relay batch message issue

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-messages-sol#268]
```
FeeMarket:  1 --> A , 2 -->B, 3 --> C
```
1. If C relay the newest header, A, B must relay 1,2,3 message.
2. C must wait A and B relay their message.

**Comment by HackFisher** [comment]
why C can not relay 1 and 2 together?

**Comment by hujw77** [comment]
C could relay 1 and 2, but it is A and B 's message.
