### ISSUE TITLE
evm -> xcm dispatch revert confirm

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-messages-sol#320]
```
function send_xcm() {
    xcm_call();
    revert();
}
```
After inbound.send_xcm(). Does `xcm_call` revert?

**Comment by wuminzhe** [comment]
The `revert()` you added here will revert the `xcm_call` the xcm will not be sent out. That's what we expect.

If the `send_xcm ` is the target function called by messaging layer. That is, any revert happened in `send_xcm()` will propagate to messaging layer. The messaging layer will emit an MessageDelivered with a success or failure result of `send_xcm`.
