### ISSUE TITLE
`MAX_PENDING_MESSAGES` might not be approximate

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-messages-sol#92]
`MAX_PENDING_MESSAGES` might not be approximate here, since it it only storing message data, and we can limit buffer using `MAX_UNCONFIRMED_MESSAGES` when delivering messages on target chain(relayers will help handle this.).

Beside, the side effect is it will limit the usage from client, and cause bad UX.

_Originally posted by @HackFisher in https://github.com/darwinia-network/darwinia-bridge-sol/pull/77#r753075550_

**Comment by hujw77** [comment]
At serial channel, the proof needs all leaves/messages. `MAX_PENDING_MESSAGES` is necessary now.
At parallel channel, there is no limit such as `MAX_PENDING_MESSAGES`, `MAX_CALLDATA_LENGTH` etc...
